### PR TITLE
Rubocop

### LINKED ISSUE #24: Rubocop styling?
This is a personal preference so I want to make sure this is alright before starting out. 

I would like the gem to pass Rubocop for readability sake. I can go over those in a pull request if you would like to see an example.

### PR DESCRIPTION
**Pull request by michaelachrisco**
Closes #24

### CODE REVIEW

**Comment by michaelachrisco** [comment]
It might be more productive to rubocop each file rather than the entire project but Ill let you guys decide. Let me know if this works out for you. 

Also, #25 should tell me if these changes are braking for ruby 1.9 since I ran this rubocop on 2.2

**Comment by chrismetcalf** [comment]
This one is going to take me a bit of time to read through. Looking now. :)

**Comment by michaelachrisco** [comment]
Now that you have travis, I can break it down file by file if need be and make sure each passes for different versions of ruby. I know that some of these changes will break older versions of ruby. I also added in thoughtbots rubocop config but feel free to browse through and remove/add any suggestions.

**Comment by chrismetcalf** [comment]
@michaelachrisco Thanks, I looked through it and the changes all look pretty reasonable. Did they pass the tests locally? I didn't see anything that'd introduce breaking changes in my code read.

Also, I am now embarrassed by my Rubies :disappointed: 

@housepage Can I get your :eyes: on this too?

**Comment by michaelachrisco** [comment]
Locally all the tests pass. But travis should take care of anything I am missing. :+1:

**Comment by chrismetcalf** [comment]
Woot.

**Comment by michaelachrisco** [comment]
Looks like 2.2 might have some issues. I would suggest not merging until #27 is passing.

**Comment by housepage** [comment]
@chrismetcalf Giving this a look now. @michaelachrisco Can you can get this branch back in an automergeable state please?

**Comment by housepage** [comment]
Everything looks good to me. Did the rebase, added rubocop as a dependency, added a rake task, and added it to the travis build in #30.

**Pull request closed without merging**
