### PR TITLE
Rubocop and update on gems

### PR DESCRIPTION
**Pull request by michaelachrisco**
Small DRY and break down for rubocop. 
General update on gems. 
Use Hashie in favor of symbolizing keys from config.

### CODE REVIEW

**Comment by chrismetcalf** [comment]
Thank you once again for making me feel slightly ashamed of my Ruby ;)

I owe you a :beer:!

**Comment by michaelachrisco** [comment]
No problem, we use this gem to retrieve records all the time, just glad to help!

**Comment by chrismetcalf** [comment]
@michaelachrisco If I can ask, what are you building and what data are you using?

**Comment by michaelachrisco** [comment]
@chrismetcalf two different projects. At the moment, it pulls hospital data for a report building process (closed source rails app) and another that pulls diseases. Not a huge amount going on as both are pretty simple one off contracts. They were built right before my current position which uses COBOL/PHP and almost no Ruby. I am trying to put in at least 1 hour of dev work a day in Ruby to keep up my skills. Any work you want to see in the gem? 

I believe I got introduced to the gem/data sets during a hack-a-thon in town. Why do you ask?

**Comment by chrismetcalf** [comment]
Thanks @michaelachrisco! I was just curious, I like to know what people are building so that I can better support them. 

Is there any functionality missing from the gem that you'd like to see, at least that you haven't already helped address? Was it pretty easy to get started with?

**Comment by michaelachrisco** [comment]
Its easy enough. Looks like there is a few features on the Java side of things but no Ruby version (which makes for a sad Ruby Dev). Currently working on fleshing it out so I can import from csv files.

**Comment by chrismetcalf** [comment]
Thanks!

**Pull request merged**
